package java_uf_application;

import java.sql.Timestamp;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author enzol
 */
public class GestionAgences extends javax.swing.JFrame {

    /**
     * Creates new form GestionAgences
     */
    AGENCES agences = new AGENCES();
    public GestionAgences() {
        initComponents();
        
        agences.fillAgencesJTable(jTableAgences);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIDAgence = new javax.swing.JTextField();
        jTextFieldLieuAgence = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAgences = new javax.swing.JTable();
        jButtonAddAgence = new javax.swing.JButton();
        jButtonEditAgence = new javax.swing.JButton();
        jButtonSupprAgence = new javax.swing.JButton();
        jButtonClearField = new javax.swing.JButton();
        jButtonRefreshJTable = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(42, 62, 80));

        jPanel2.setBackground(new java.awt.Color(102, 0, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion des agences");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID :");

        jTextFieldIDAgence.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldLieuAgence.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lieu :");

        jTableAgences.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Lieu", "Créée le", "Mise à jour le"
            }
        )
        //Table plus modifiable
        {public boolean isCellEditable(int row, int column) {return false;}}

    );
    jTableAgences.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTableAgencesMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTableAgences);

    jButtonAddAgence.setBackground(new java.awt.Color(0, 153, 51));
    jButtonAddAgence.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
    jButtonAddAgence.setText("Ajouter une nouvelle agence");
    jButtonAddAgence.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonAddAgence.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonAddAgenceActionPerformed(evt);
        }
    });

    jButtonEditAgence.setBackground(new java.awt.Color(255, 255, 0));
    jButtonEditAgence.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
    jButtonEditAgence.setText("Modifier une agence existante");
    jButtonEditAgence.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonEditAgence.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonEditAgenceActionPerformed(evt);
        }
    });

    jButtonSupprAgence.setBackground(new java.awt.Color(204, 0, 0));
    jButtonSupprAgence.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
    jButtonSupprAgence.setText("Supprimer une agence");
    jButtonSupprAgence.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonSupprAgence.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonSupprAgenceActionPerformed(evt);
        }
    });

    jButtonClearField.setBackground(new java.awt.Color(102, 0, 255));
    jButtonClearField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
    jButtonClearField.setText("Effacer les champs");
    jButtonClearField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonClearField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonClearFieldActionPerformed(evt);
        }
    });

    jButtonRefreshJTable.setBackground(new java.awt.Color(102, 0, 255));
    jButtonRefreshJTable.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
    jButtonRefreshJTable.setText("Refresh");
    jButtonRefreshJTable.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonRefreshJTableActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(54, 54, 54)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonClearField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSupprAgence, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEditAgence, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAddAgence, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldLieuAgence, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldIDAgence, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(80, 80, 80)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
            .addContainerGap())
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonRefreshJTable, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(94, 94, 94))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextFieldIDAgence, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextFieldLieuAgence, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(136, 136, 136)
                    .addComponent(jButtonAddAgence, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jButtonEditAgence, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addComponent(jButtonSupprAgence, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jButtonClearField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButtonRefreshJTable)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableAgencesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAgencesMouseClicked
        // Afficher les données de la ligne du tableau sélectionnée dans les champs

        // Avoir le model du tableau jTable*
        DefaultTableModel model = (DefaultTableModel)jTableAgences.getModel();

        int rIndex = jTableAgences.getSelectedRow();

        jTextFieldIDAgence.setText(model.getValueAt(rIndex, 0).toString());
        jTextFieldLieuAgence.setText(model.getValueAt(rIndex, 1).toString());

    }//GEN-LAST:event_jTableAgencesMouseClicked

    private void jButtonAddAgenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddAgenceActionPerformed
        //Ajout d'une agence

        //Récupération des données des champs d'entré
        String lieu = jTextFieldLieuAgence.getText();
        Timestamp created_at = java.sql.Timestamp.from(java.time.Instant.now());
        Timestamp updated_at = java.sql.Timestamp.from(java.time.Instant.now());

        if(lieu.trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Champs vides", "Champs Vides", JOptionPane.WARNING_MESSAGE);
        }else {
            if(agences.addAgence(lieu, created_at, updated_at)){
                JOptionPane.showMessageDialog(rootPane, "Nouvelle agence ajoutée", "Ajout agence", JOptionPane.INFORMATION_MESSAGE);

            }else{
                JOptionPane.showMessageDialog(rootPane, "Erreur dans l'ajout de nouvelle agence", "Erreur d'Ajout agence", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_jButtonAddAgenceActionPerformed

    private void jButtonEditAgenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditAgenceActionPerformed
        
        //Récupération des données des champs d'entrés
        int id = 0;
        String lieu = jTextFieldLieuAgence.getText();
        Timestamp updated_at = java.sql.Timestamp.from(java.time.Instant.now());

        if(lieu.trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Champs vides", "Champs Vides", JOptionPane.WARNING_MESSAGE);
        }else {

            try{
                id = Integer.valueOf(jTextFieldIDAgence.getText());

                if(agences.modifierAgence(id, lieu, updated_at)){
                    JOptionPane.showMessageDialog(rootPane, "Infos de l'agence modifiées avec succès", "Modification Agence", JOptionPane.INFORMATION_MESSAGE);

                }else{
                    JOptionPane.showMessageDialog(rootPane, "Erreur dans la modification des infos de l'agence", "Erreur de modification Agence", JOptionPane.ERROR_MESSAGE);
                }

            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Veuillez d'abord entrer l'ID de l'agence à modifier ou le sélectionner dans le tableau", "Erreur ID Agence", JOptionPane.ERROR_MESSAGE);
            }

        }

    }//GEN-LAST:event_jButtonEditAgenceActionPerformed

    private void jButtonSupprAgenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprAgenceActionPerformed

        // Supprimer l'agence sélectionnée

        try{
            int id = Integer.valueOf(jTextFieldIDAgence.getText());

            if(agences.supprimerAgence(id)){
                JOptionPane.showMessageDialog(rootPane, "Agence supprimée avec succès", "Suppression Agence", JOptionPane.INFORMATION_MESSAGE);

            }else{
                JOptionPane.showMessageDialog(rootPane, "L'agence n'a pas été supprimée ", "Erreur de suppression Agence", JOptionPane.ERROR_MESSAGE);
            }

        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Veuillez d'abord entrer l'ID de l'agence à supprimer ou le sélectionner dans le tableau", "Erreur ID Agence", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSupprAgenceActionPerformed

    private void jButtonClearFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearFieldActionPerformed
        // Enlever le texte présent sur les champs d'entré
        jTextFieldIDAgence.setText("");
        jTextFieldLieuAgence.setText("");
    }//GEN-LAST:event_jButtonClearFieldActionPerformed

    private void jButtonRefreshJTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshJTableActionPerformed
        // Rafraichis les données de la BDD dans le tableau
        // On vide d'abord le tableau
        jTableAgences.setModel(new DefaultTableModel(null, new Object[]{"ID","Lieu","Créée le","Mise à jour le"}));

        //Puis on le remplis
        agences.fillAgencesJTable(jTableAgences);
    }//GEN-LAST:event_jButtonRefreshJTableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionAgences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionAgences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionAgences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionAgences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionAgences().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddAgence;
    private javax.swing.JButton jButtonClearField;
    private javax.swing.JButton jButtonEditAgence;
    private javax.swing.JButton jButtonRefreshJTable;
    private javax.swing.JButton jButtonSupprAgence;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAgences;
    private javax.swing.JTextField jTextFieldIDAgence;
    private javax.swing.JTextField jTextFieldLieuAgence;
    // End of variables declaration//GEN-END:variables
}
