/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_uf_application;

import java.awt.Image;
import java.io.File;
import java.sql.Blob;
import java.sql.Timestamp;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author enzol
 */
public class GestionDocs extends javax.swing.JFrame {

    /**
     * Creates new form GestionDocs
     */
    DOCUMENTS documents = new DOCUMENTS();
    String image_path = "";
    String mandat_path = "";
    String contrat_path = "";
    public ImageIcon Format = null;
    int id_bien;
    public GestionDocs() {
        initComponents();
        
        documents.fillDocsJTable(jTableDocs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIDBien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDocs = new javax.swing.JTable();
        jButtonAddDocs = new javax.swing.JButton();
        jButtonEditDocs = new javax.swing.JButton();
        jButtonSupprDocs = new javax.swing.JButton();
        jButtonClearField = new javax.swing.JButton();
        jButtonRefreshJTable = new javax.swing.JButton();
        jButtonMandat = new javax.swing.JButton();
        jButtonContrat = new javax.swing.JButton();
        jButtonImage = new javax.swing.JButton();
        jLabelImage = new javax.swing.JLabel();
        jLabelMandat = new javax.swing.JLabel();
        jLabelContrat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(42, 62, 80));

        jPanel2.setBackground(new java.awt.Color(0, 51, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion des documents");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(505, 505, 505))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID_Bien :");

        jTextFieldIDBien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mandat :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contrat :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Image :");

        jTableDocs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Bien", "ID_Vendeur", "ID_Agent", "Mandat", "Contrat", "Image"
            }
        )
        //Table plus modifiable
        {
            public boolean isCellEditable(int row, int column)
            {
                return false;
            }
        }

    );
    jTableDocs.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTableDocsMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTableDocs);

    jButtonAddDocs.setBackground(new java.awt.Color(0, 153, 51));
    jButtonAddDocs.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
    jButtonAddDocs.setText("Ajouter Nouveaux Documents");
    jButtonAddDocs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonAddDocs.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonAddDocsActionPerformed(evt);
        }
    });

    jButtonEditDocs.setBackground(new java.awt.Color(255, 255, 0));
    jButtonEditDocs.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
    jButtonEditDocs.setText("Modifier Documents Existants");
    jButtonEditDocs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonEditDocs.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonEditDocsActionPerformed(evt);
        }
    });

    jButtonSupprDocs.setBackground(new java.awt.Color(204, 0, 0));
    jButtonSupprDocs.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
    jButtonSupprDocs.setText("Supprimer Tous les Documents d'un Bien");
    jButtonSupprDocs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonSupprDocs.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonSupprDocsActionPerformed(evt);
        }
    });

    jButtonClearField.setBackground(new java.awt.Color(51, 51, 255));
    jButtonClearField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
    jButtonClearField.setText("Effacer les champs");
    jButtonClearField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonClearField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonClearFieldActionPerformed(evt);
        }
    });

    jButtonRefreshJTable.setBackground(new java.awt.Color(51, 51, 255));
    jButtonRefreshJTable.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
    jButtonRefreshJTable.setText("Refresh");
    jButtonRefreshJTable.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonRefreshJTableActionPerformed(evt);
        }
    });

    jButtonMandat.setText("Ouvrir fichier");
    jButtonMandat.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonMandatActionPerformed(evt);
        }
    });

    jButtonContrat.setText("Ouvrir fichier");
    jButtonContrat.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonContratActionPerformed(evt);
        }
    });

    jButtonImage.setText("Ouvrir fichier");
    jButtonImage.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonImageActionPerformed(evt);
        }
    });

    jLabelImage.setBackground(new java.awt.Color(102, 204, 255));
    jLabelImage.setOpaque(true);

    jLabelMandat.setBackground(new java.awt.Color(102, 204, 255));
    jLabelMandat.setOpaque(true);

    jLabelContrat.setBackground(new java.awt.Color(102, 204, 255));
    jLabelContrat.setOpaque(true);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonRefreshJTable, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(238, 238, 238))
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonMandat, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldIDBien, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabelMandat, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonClearField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSupprDocs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAddDocs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEditDocs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGap(24, 24, 24)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonContrat, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabelContrat, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonImage, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(54, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButtonContrat))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButtonMandat))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButtonImage)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addComponent(jLabelContrat, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addComponent(jLabelMandat, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextFieldIDBien, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(59, 59, 59)
                    .addComponent(jButtonAddDocs, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jButtonEditDocs, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jButtonSupprDocs, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jButtonClearField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButtonRefreshJTable)
            .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableDocsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDocsMouseClicked
        // Afficher les données de la ligne du tableau sélectionnée dans les champs

        // Avoir le model du tableau jTable*
        DefaultTableModel model = (DefaultTableModel)jTableDocs.getModel();

        int rIndex = jTableDocs.getSelectedRow();

        jTextFieldIDBien.setText(model.getValueAt(rIndex, 0).toString());
        /*Format = new ImageIcon((String) model.getValueAt(rIndex, 5));
        jLabelMandat.setIcon((Icon) model.getValueAt(rIndex, 3));
        jLabelContrat.setIcon((Icon) model.getValueAt(rIndex, 4));
        jLabelImage.setIcon(Format);*/
    }//GEN-LAST:event_jTableDocsMouseClicked

    private void jButtonAddDocsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddDocsActionPerformed
        //Ajout d'un client

        //Récupération des données des champs d'entré
        int id_bien = Integer.valueOf(jTextFieldIDBien.getText());
        Blob image = null ;
        Blob mandat = null ;
        Blob contrat = null ;
        Timestamp updated_at = new java.sql.Timestamp(new java.util.Date().getTime());

        if(jTextFieldIDBien.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Veuillez entrer au moins l'ID du bien", "Champs Vides", JOptionPane.WARNING_MESSAGE);
        }else {
            if(documents.addDocs(id_bien, image_path, mandat_path, contrat_path, updated_at)){
                JOptionPane.showMessageDialog(rootPane, "Nouveaux Documents ajoutés avec succès", "Ajout Documents", JOptionPane.INFORMATION_MESSAGE);

            }else{
                JOptionPane.showMessageDialog(rootPane, "Erreur dans l'ajout de nouveaux documents du bien", "Erreur d'Ajout de documents", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_jButtonAddDocsActionPerformed

    private void jButtonEditDocsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditDocsActionPerformed

        //Récupération des données des champs d'entrés
        int id_bien = Integer.valueOf(jTextFieldIDBien.getText());
        Timestamp updated_at = new java.sql.Timestamp(new java.util.Date().getTime());

        if(jTextFieldIDBien.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Veuillez entrer au moins l'ID du propriétaire du bien", "Champs Vides", JOptionPane.WARNING_MESSAGE);
        }else {

            try{
                id_bien = Integer.valueOf(jTextFieldIDBien.getText());

                if(documents.modifierDocs(id_bien, image_path, mandat_path, contrat_path, updated_at)){
                    JOptionPane.showMessageDialog(rootPane, "Documents modifiés avec succès", "Modification Documents", JOptionPane.INFORMATION_MESSAGE);

                }else{
                    JOptionPane.showMessageDialog(rootPane, "Erreur dans la modification des documents", "Erreur de modification des documents", JOptionPane.ERROR_MESSAGE);
                }

            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Veuillez d'abord entrer l'ID du bien ", "Erreur ID Bien", JOptionPane.ERROR_MESSAGE);
            }

        }

    }//GEN-LAST:event_jButtonEditDocsActionPerformed

    private void jButtonSupprDocsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprDocsActionPerformed

         //Récupération des données des champs d'entrés pour ensuite les rendre null dans la requête quoi qu'il arrive
        int id_bien = Integer.valueOf(jTextFieldIDBien.getText());
        Timestamp updated_at = new java.sql.Timestamp(new java.util.Date().getTime());
        
        // Supprimer le client sélectionné
        try{
            int id = Integer.valueOf(jTextFieldIDBien.getText());

            if(documents.supprimerDocs(id, image_path, mandat_path, contrat_path, updated_at)){
                JOptionPane.showMessageDialog(rootPane, "Documents du bien supprimés avec succès", "Suppression Documents", JOptionPane.INFORMATION_MESSAGE);

            }else{
                JOptionPane.showMessageDialog(rootPane, "Les documents n'ont pas été supprimés ", "Erreur de suppression des documents", JOptionPane.ERROR_MESSAGE);
            }

        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Veuillez d'abord entrer l'ID du Bien pour supprimer ses documents", "Erreur ID Bien", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSupprDocsActionPerformed

    private void jButtonClearFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearFieldActionPerformed
        // Enlever le texte présent sur les champs d'entré
        jTextFieldIDBien.setText("");
        jLabelContrat.setText("");
        jLabelContrat.setIcon(null);
        jLabelImage.setText("");
        jLabelImage.setIcon(null);
        jLabelMandat.setText("");
        jLabelMandat.setIcon(null);
        contrat_path = "";
        mandat_path = "";
        image_path = "";
    }//GEN-LAST:event_jButtonClearFieldActionPerformed

    private void jButtonRefreshJTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshJTableActionPerformed
        // Rafraichis les données de la BDD dans le tableau
        // On vide d'abord le tableau
        jTableDocs.setModel(new DefaultTableModel(null, new Object[]{"ID_Bien", "ID_Vendeur", "ID_Agent", "Mandat", "Contrat", "Image"}));

        //Puis on le remplis
        documents.fillDocsJTable(jTableDocs);
    }//GEN-LAST:event_jButtonRefreshJTableActionPerformed

    public ImageIcon resizeImage(String path){
        // Fonction permettant de redimensionner les images par rapport aux cadres
        Image img = new ImageIcon(path).getImage().getScaledInstance(jLabelImage.getWidth(), jLabelImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img);
        return image;      
    }
    
    private void jButtonMandatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMandatActionPerformed
        // Chercher le fichier du mandat sur l'ordinateur
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Choisissez le document du mandat approprié");
        fileChooser.setCurrentDirectory(new File("C:\\"));
        
        //Trier et choisir les extensions de fichier
        FileNameExtensionFilter filfilter =  new FileNameExtensionFilter("Documents", ".jpg",".png",".jpeg",".odt",".pdf",".docx");
        fileChooser.addChoosableFileFilter(filfilter);
        
        int fileState = fileChooser.showSaveDialog(null);
        
        if (fileState == JFileChooser.APPROVE_OPTION) {
            String path = fileChooser.getSelectedFile().getAbsolutePath();
            jLabelMandat.setIcon(resizeImage(path));
            mandat_path = path;
        }
    }//GEN-LAST:event_jButtonMandatActionPerformed

    private void jButtonContratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContratActionPerformed
        // Chercher le fichier du contrat sur l'ordinateur
        JFileChooser fileChooser2 = new JFileChooser();
        fileChooser2.setDialogTitle("Choisissez le document du contrat approprié");
        fileChooser2.setCurrentDirectory(new File("C:\\"));
        
        //Trier et choisir les extensions de fichier
        FileNameExtensionFilter filfilter2 =  new FileNameExtensionFilter("Documents", ".jpg",".png",".jpeg",".odt",".pdf",".docx");
        fileChooser2.addChoosableFileFilter(filfilter2);
        
        int fileState2 = fileChooser2.showSaveDialog(null);
        
        if (fileState2 == JFileChooser.APPROVE_OPTION) {
            String path = fileChooser2.getSelectedFile().getAbsolutePath();
            jLabelContrat.setIcon(resizeImage(path));
            contrat_path = path;
        }
    }//GEN-LAST:event_jButtonContratActionPerformed

    private void jButtonImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImageActionPerformed
        // Chercher le fichier d'image sur l'ordinateur
        JFileChooser fileChooser3 = new JFileChooser();
        fileChooser3.setDialogTitle("Choisissez l'image appropriée");
        fileChooser3.setCurrentDirectory(new File("C:\\"));
        
        //Trier et choisir les extensions de fichier
        FileNameExtensionFilter filfilter3 =  new FileNameExtensionFilter("Images", ".jpg",".png",".jpeg");
        fileChooser3.addChoosableFileFilter(filfilter3);
        
        int fileState3 = fileChooser3.showSaveDialog(null);
        
        if (fileState3 == JFileChooser.APPROVE_OPTION) {
            String path = fileChooser3.getSelectedFile().getAbsolutePath();
            jLabelImage.setIcon(resizeImage(path));
            image_path = path;
        }
    }//GEN-LAST:event_jButtonImageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionDocs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionDocs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionDocs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionDocs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionDocs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddDocs;
    private javax.swing.JButton jButtonClearField;
    private javax.swing.JButton jButtonContrat;
    private javax.swing.JButton jButtonEditDocs;
    private javax.swing.JButton jButtonImage;
    private javax.swing.JButton jButtonMandat;
    private javax.swing.JButton jButtonRefreshJTable;
    private javax.swing.JButton jButtonSupprDocs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelContrat;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelMandat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDocs;
    private javax.swing.JTextField jTextFieldIDBien;
    // End of variables declaration//GEN-END:variables
}
